version: "3.8"

services:
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369" # for clastering
    - "5671:5671"
    - "5672:5672" # main port for communication
    - "25672:25672"
    - "15671:15671"
    - "15672:15672" # RabbitMQ Management console
    # healthcheck:
    #     test: ["CMD", "curl", "-f", "http://localhost:15672"]
    #     interval: 30s
    #     timeout: 10s
    #     retries: 5
    logging:
      driver: none # disabling logs
  db:
      build: ./sql
      ports:
          - "1433:1433"
      environment:
          SA_PASSWORD: "STRONGpassword123!"
          ACCEPT_EULA: "Y"
      logging:
          driver: none # disabling logs
          
  receiverget:
    build: ./receiverGet/
    restart: always
    depends_on:
      - rabbitmq
      - db
      
  receiverprzelew:
    build: ./receiverPrzelew/
    restart: always
    depends_on:
      - rabbitmq
      - db
        
  sender:
    build: ./sender/
    restart: always
    ports:
        - "8000:80"
        
  front:
    build: ./frontend/
    restart: always
    ports:
        - "80:80"
