version: "3.8"

services:
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369" # for clustering
    - "5671:5671"
    - "5672:5672" # main port for communication
    - "25672:25672"
    - "15671:15671"
    - "15672:15672" # RabbitMQ Management console
    logging:
      driver: none # disabling logs
  accounts_db:
      build: ./accounts_db/
      ports:
          - "1433:1433"
      environment:
          SA_PASSWORD: "STRONGpassword123!"
          ACCEPT_EULA: "Y"
      logging:
          driver: none # disabling logs
          
  receiverget:
    build: ./receiverGet/
    restart: always
    depends_on:
      - rabbitmq
      - accounts_db
      
  receiverprzelew:
    build: ./receiverPrzelew/
    restart: always
    depends_on:
      - rabbitmq
      - accounts_db
        
  sender:
    build: ./sender/
    restart: always
    ports:
        - "8000:80"
        
  front:
    build: ./frontend/
    restart: always
    ports:
        - "80:80"
          
  databaseinit:
    build: ./DatabaseInit/
       
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafkaconsumer:
    build: ./KafkaConsumer/
    restart: always
    